@startuml
artifact Goverment <<1 Бизнес стратегия Организации>> {
control LongTime <<10 лет>>

Folder TechnologyDomains {
collections TechStackGoverment
}

artifact Enterprise <<2 Технологическая стратегия Организации>> {
Folder PlatformsEnterprise {
collections TechStackEnterprise
collections ADREnterprise
collections Services_Enterprise
ADREnterprise -left- Services_Enterprise
Services_Enterprise -left-> TechStackEnterprise 
}


control Yearly <<1 год>>
artifact Solution <<3 Целевая архитектура Организации>> {
Folder PlatformsSolution {
collections TechStackSolution
collections ADRSolution
collections Services_Solution
Services_Solution -left-> TechStackSolution 
ADRSolution -left- Services_Solution
}
control Quarterly <<1 квартал>>
artifact "Release Train" as Release <<4 Архитектура Домена Организации>> {
control Monthly <<1 месяц>>
Folder PlatformReleased {
collections TechStackReleased
collections ADRReleased
collections Services_Released
TechStackReleased <-right- Services_Released
Services_Released -left- ADRReleased
}
artifact Backlog <<5 Архитектура решения Организации>> {
control Weekly <<1 неделя>>
Folder Platforms <<Бэклог команд разработки>> {
collections "Services & Features" as  Services
collections TechStacBacklog
collections Integrations
Services -left-> TechStacBacklog
Integrations <-left- Services
     }
    }
   }
  }
 }
}

PlatformsEnterprise -up-> TechnologyDomains
PlatformsSolution -up-> PlatformsEnterprise
PlatformReleased -up-> PlatformsSolution
Platforms -up-> PlatformReleased

Services_Solution -up-> Services_Enterprise
Services_Released -up-> Services_Solution
Services -up-> Services_Released

ADRSolution -up-> ADREnterprise
ADRReleased -up-> ADRSolution
Integrations -up-> ADRReleased
@endum
